### ISSUE TITLE
ForegroundServiceStartNotAllowedException being thrown when attempting to start the arrival and proximity alert services

### ISSUE THREAD

**Issue by NiallScott** [NiallScott/MyBusEdinburgh#26]
A crash was being encountered in version 3.0.1;

```
Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service uk.org.rivernile.edinburghbustracker.android/uk.org.rivernile.android.bustracker.core.alerts.proximity.ProximityAlertRunnerService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
       at android.os.Parcel.readParcelable(Parcel.java:4755)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
       at android.os.Parcel.createException(Parcel.java:3007)
       at android.os.Parcel.readException(Parcel.java:2990)
       at android.os.Parcel.readException(Parcel.java:2932)
       at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6201)
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1967)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
       at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java)
       at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:6)
       at uk.org.rivernile.android.bustracker.core.alerts.proximity.AndroidProximityAlertTaskLauncher.launchProximityAlertTask(AndroidProximityAlertTaskLauncher.java:11)
       at uk.org.rivernile.android.bustracker.core.alerts.AlertManager$ensureTasksRunningIfAlertsExists$2$2.invokeSuspend(AlertManager.java:55)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:88)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)
```

This is presumably due to the new foreground service restrictions introduced in Android 12;
https://developer.android.com/guide/components/foreground-services
https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions

This was never encountered in testing, but is being experienced in the wild.

A temporary fix has been put in place to catch the exception and log it, to stop the app crashing and prevent the app from being unusable. However, this would mean the services aren't running, and users won't be receiving their expected alerts. So the proper fix would involve running the services to expectation.

**Comment by NiallScott** [comment]
An enhancement was made in https://github.com/NiallScott/MyBusEdinburgh/commit/1a268ac50f3c90ae83dc5d6807654144b2c763d5 to start the alert services synchronously in `DeviceBootBroadcastReceiver.onReceive()` so that the services are being started while we're still handling the `BOOT_COMPLETED` `Intent`. This should hopefully reduce the chance of the OS rejecting our request to start the services.

Also, as an enhancement, we now handle the `MY_PACKAGE_REPLACED` `Intent` so that our alerts are given a chance to resume after an update of the app.

After reading the foreground service launch restrictions guide, there doesn't appear to be any other way to handle this within the capabilities of this app. So the correct thing to do is the emergency fix as mentioned in the issue blurb, which is to wrap the call to start the services in a `try-catch` handler and hope for the best. If we can't start the services, that's crappy but we've made a best effort and Android is preventing us.
